config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :clubs
  resources :users
  root 'welcome#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/clubs/index.html.erb
<div class="clubs">
  <ul>
    <li><a href="#"><img src="http://placehold.it/150x150" /></a></li>
    <li><a href="#"><img src="http://placehold.it/150x150" /></a></li>
    <li><a href="#"><img src="http://placehold.it/150x150" /></a></li>
    <li><a href="#"><img src="http://placehold.it/150x150" /></a></li>
    <li><a href="#"><img src="http://placehold.it/150x150" /></a></li>
    <li><a href="#"><img src="http://placehold.it/150x150" /></a></li>
    <li><a href="#"><img src="http://placehold.it/150x150" /></a></li>
    <li><a href="#"><img src="http://placehold.it/150x150" /></a></li>
    <li><a href="#"><img src="http://placehold.it/150x150" /></a></li>
    <li><a href="#"><img src="http://placehold.it/150x150" /></a></li>
    <li><a href="#"><img src="http://placehold.it/150x150" /></a></li>
    <li><a href="#"><img src="http://placehold.it/150x150" /></a></li>
    <li><a href="#"><img src="http://placehold.it/150x150" /></a></li>
    <li><a href="#"><img src="http://placehold.it/150x150" /></a></li>
    <li><a href="#"><img src="http://placehold.it/150x150" /></a></li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
  <title>GAMEHUB</title>
</head>
<body>
  <div class="navbar">
    <ul>
      <li><%= link_to "GAMEHUB", root_path %></li>
      <li><%= link_to "Clubs", clubs_path(@index) %></li>
      <li style="float:right"><%= link_to "Sign in", 'users/new' %></li>
    </ul>
  </div>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<div class="login-page">
<div class="form">
  <form class="register-form">
    <input type="text" placeholder="име"/>
    <input type="password" placeholder="парола"/>
    <input type="password" placeholder="Повтори парола"/>
    <input type="text" placeholder="е-мейл"/>
    <button>създай!</button>
    <p class="message">Вече регистрирани? <a href="#">Впиши ме</a></p>
  </form>
  <form class="login-form">
    <input type="text" placeholder="потребителско име"/>
    <input type="password" placeholder="парола"/>
    <button>влез</button>
    <p class="message">Не си регистриран? <a href="#">Създай акаунт</a></p>
  </form>
</div>
</div>
<script type="text/javascript">
  $('.message a').click(function(){
  $('form').animate({height: "toggle", opacity: "toggle"}, "slow");
  });
</script>

app/views/welcome/index.html.erb
<!-- <div id="googlemaps"></div> -->
<div id="contactform">
  <div id="input_form">
    <input type="text" placeholder="Къде/какво ми се играе?" autocomplete="off">
  </div>
</div>

<!-- <script src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>

<script type="text/javascript">

var position = [42.69766088956656, 23.318090949707084];

function showGoogleMaps() {

    var latLng = new google.maps.LatLng(position[0], position[1]);

    var mapOptions = {
        zoom: 16, // initialize zoom level - the max value is 21
        streetViewControl: false, // hide the yellow Street View pegman
        scaleControl: true, // allow users to zoom the Google Map
        mapTypeId: google.maps.MapTypeId.ROADMAP,
        center: latLng
    };

    map = new google.maps.Map(document.getElementById('googlemaps'),
        mapOptions);

    // Show the default red marker at the location
    marker = new google.maps.Marker({
        position: latLng,
        map: map,
        draggable: false,
        animation: google.maps.Animation.DROP
    });
}

google.maps.event.addDomListener(window, 'load', showGoogleMaps);
</script>


 -->